### ISSUE TITLE
MMCONNECT (MINIMED CONNECT BRIDGE)

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/nightscout.github.io#137]
@psonnera  and @bewest 

I just came across this. Is this still accurate after the latest NS release? 

http://nightscout.github.io/nightscout/setup_variables/?h=openaps#mmconnect-minimed-connect-bridge

`This plugin is NOT functional with Heroku: do not enable it. `

https://github.com/nightscout/cgm-remote-monitor/releases/tag/14.2.5

**Comment by psonnera** [comment]
@bjornoleh I don't have feedback from beta testers. Do you?

**Comment by bjornoleh** [comment]
No, I have no idea beyond the release notes and the PRs that went into that release. Ben might know more.

**Comment by psonnera** [comment]
Tried an European account and got 403. Another US user same.

**Comment by bewest** [comment]
Thanks for testing.  It appears public hosting platforms like Heroku tend to get blocked.  It still appears that doing this from a mobile rig, or a "sidecar" deployment still works, or on private infrastructure still works.

Is there a page/directory to add a permalink for issues like this to add more details?
Thanks for all the testing and contributions.

**Comment by bewest** [comment]
Am considering deprecating this plugin without additional contributions.  [xdripCarelinkFollower](https://github.com/benceszasz/xDripCareLinkFollower) does a great job of copying data from Medtronic cloud and copying it to Nightscout.  We need additional contributors to ensure the plugin matches the expected behavior and to verify usability within different environments.

There may be additional challenges, such as MFA threatening the technical viability of this plugin. https://github.com/nightscout/minimed-connect-to-nightscout/issues/34

I've heard of some success from people using sidecar modules as well.

**Comment by psonnera** [comment]
@bewest please don't. The plugin might work on home hosted servers. We need to try it on new solutions. We know Heroku and others are blacklisted but maybe some aren't. Also some hosted services might use it. @ktomy ?

**Comment by bewest** [comment]
No worries, I'm in no rush to deprecate it and it will issue deprecation warnings when used before it gets removed.  My concern is that this isn't actually working for anyone without changes. So it may be time to start issuing warnings if this feature gets turned on.

**Comment by psonnera** [comment]
@petervanrijt was that tried on Synology? If the plugin is functional I'd believe a home based IP might not be blocked...
PS: Terry says it doesn't work on Railway...

**Comment by bewest** [comment]
I've mentioned before I think it's more than a blocking issue; there may be changes required as well.  We need to do a careful audit of xdripcarelinkfollower to make sure we're using the same strategy for authentication.  In theory it should work well on synology, good catch @psonnera.  If there were no issues with the code I would expect it to work on Railway; since it doesn't it hints something is wrong with the code myself.  Additional help and testing details are of course welcome.

**Comment by petervanrijt** [comment]
We are not using it. But I can provide quickly a test environment for it, if someone has the equipment and time for testing :)

**Comment by psonnera** [comment]
The new plugin is under testing (available in dev) and this will be the final solution. mmconnect will be deprecated in the future.
https://github.com/nightscout/nightscout-connect#minimed-carelink
